/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarioycontraseña;

import javax.swing.JOptionPane;

/**
 *
 * @author NatyMel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Textusuario = new javax.swing.JTextField();
        Textpass = new javax.swing.JPasswordField();
        BTNAceptar = new javax.swing.JButton();
        BTNSalir = new javax.swing.JButton();
        BTNHelp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/programming-for-kids.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 186, 227));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 65)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoJL100.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/87466 - security.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, 10));

        Textusuario.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Textusuario.setBorder(null);
        Textusuario.setOpaque(false);
        getContentPane().add(Textusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 170, -1));

        Textpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Textpass.setBorder(null);
        Textpass.setOpaque(false);
        getContentPane().add(Textpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 170, -1));

        BTNAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/105212 - accept agree approved check checkmark choice corre.png"))); // NOI18N
        BTNAceptar.setBorder(null);
        BTNAceptar.setContentAreaFilled(false);
        BTNAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 60, 50));

        BTNSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23360 - gtk image missing.png"))); // NOI18N
        BTNSalir.setBorder(null);
        BTNSalir.setBorderPainted(false);
        BTNSalir.setContentAreaFilled(false);
        BTNSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 30));

        BTNHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/105209 - help mark query question support.png"))); // NOI18N
        BTNHelp.setContentAreaFilled(false);
        BTNHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHelpActionPerformed(evt);
            }
        });
        getContentPane().add(BTNHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 30, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("Inicio de secion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/87478 - user.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/317990.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 250, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAceptarActionPerformed
        // TODO add your handling code here:
        String nombre = Textusuario.getText();
        String pas = Textpass.getText();
        
        if (nombre.equals("Administrador") && pas.equals("admin"))
        {
        JOptionPane.showMessageDialog(this,"Usuario Correcto","LOGIN",JOptionPane.INFORMATION_MESSAGE);
        Limpiar();
        }
        else
            JOptionPane.showMessageDialog(this,"Usuario o pass INCORRECTO","LOGIN",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BTNAceptarActionPerformed

    private void Limpiar()
    {
        Textusuario.setText("");
        Textpass.setText("");
    }
    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(this,"¿Esta seguro de cerrar la aplicación?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(valor == JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(null,"Gracias por la visita, hasta pronto","Gracias",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Para mas informacion enviar un mail a","LOGIN",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_BTNHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAceptar;
    private javax.swing.JButton BTNHelp;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JPasswordField Textpass;
    private javax.swing.JTextField Textusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
